#!/usr/bin/env bash
#  HAProxy load balancer config

# update the package lists
sudo apt-get -y update

# install all required packages
sudo apt-get -y install software-properties-common

# Add the HAProxy repository and install HAProxy
sudo add-apt repository -y ppa:vbernat/haproxy-2.0
sudo app-get -y update
sudo apt-get -y install haproxy

# HAProxy configurations
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend web-servers

backend web-servers
    balance roundrobin
    server 518227-web-01 3.85.33.201:80 check
    server 518227-web-02 3.94.211.105:80 check
"
# Adding your HAProxy configuration to haproxy.cfg
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo "$balancer" >> /etc/haproxy/haproxy.cfg

# Start the HAProxy service
sudo service haproxy start

