#!/usr/bin/env bash
# debugging nginx port 80

# flag -s to create a symbolic link,and-f delete existing file and replaces it
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
