#!/usr/bin/env bash
# install ufw firewall & set requirements

# update status
sudo apt-get update

# install UFW.
sudo apt-get install ufw

# enable UFW
sudo ufw enable

# set default policies
sudo ufw default deny incoming

# allow specific ports
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# enable UFW to new changes.
sudo ufw enable

# check the status
sudo ufw status
