#!/bin/bash
# Changes ownership  to nginx user
chown -R nginx:nginx /var/log/nginx /var/lib/nginx /var/www/html

# change ownership ngix files to nginx user
chown nginx:nginx /etc/nginx/nginx.conf /etc/nginx/sites-available/default

# Modify Nginx configuration to run as nginx user
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Modify Nginx default sites available to listen on all active IPs on port 8080
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default

# Restart Nginx service
service nginx restart
